import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const RAW_DIR = path.join(ROOT, 'src', 'assets', 'raw');
const OUT_DIR = path.join(ROOT, 'src', 'assets', 'encoded');
const OUT_FILE = path.join(OUT_DIR, 'assetManifest.js');

const MIME_TYPES = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.wav': 'audio/wav',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
};

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function generateToneWav(frequency, durationSec, volume = 0.3) {
  const sampleRate = 22050;
  const numSamples = Math.floor(sampleRate * durationSec);
  const dataSize = numSamples * 2;
  const buffer = Buffer.alloc(44 + dataSize);

  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(sampleRate * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);

  for (let i = 0; i < numSamples; i++) {
    const t = i / sampleRate;
    const envelope = Math.min(1, Math.min(t * 20, (durationSec - t) * 20));
    const sample = Math.sin(2 * Math.PI * frequency * t) * volume * envelope;
    buffer.writeInt16LE(Math.max(-32767, Math.min(32767, Math.floor(sample * 32767))), 44 + i * 2);
  }

  return buffer;
}

function ensureDefaultAssets() {
  ensureDir(RAW_DIR);

  const defaults = [
    { name: 'catch.wav', generator: () => generateToneWav(880, 0.12, 0.25) },
    { name: 'bomb.wav', generator: () => generateToneWav(110, 0.35, 0.35) },
    { name: 'win.wav', generator: () => generateToneWav(660, 0.2, 0.2) },
    { name: 'lose.wav', generator: () => generateToneWav(220, 0.4, 0.25) },
    { name: 'tick.wav', generator: () => generateToneWav(440, 0.05, 0.15) },
  ];

  for (const { name, generator } of defaults) {
    const filePath = path.join(RAW_DIR, name);
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, generator());
      console.log(`Generated default asset: ${name}`);
    }
  }
}

function encodeFile(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  const mime = MIME_TYPES[ext];
  if (!mime) {
    console.warn(`Skipping unsupported file: ${filePath}`);
    return null;
  }

  const data = fs.readFileSync(filePath);
  const base64 = data.toString('base64');
  const key = path.basename(filePath, ext).replace(/[^a-zA-Z0-9_-]/g, '_');

  return {
    key,
    type: mime.startsWith('audio') ? 'audio' : 'image',
    dataUri: `data:${mime};base64,${base64}`,
  };
}

function collectAssets(dir) {
  const assets = { images: {}, audio: {} };

  if (!fs.existsSync(dir)) {
    return assets;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = collectAssets(fullPath);
      Object.assign(assets.images, nested.images);
      Object.assign(assets.audio, nested.audio);
      continue;
    }

    const encoded = encodeFile(fullPath);
    if (!encoded) continue;

    if (encoded.type === 'audio') {
      assets.audio[encoded.key] = encoded.dataUri;
    } else {
      assets.images[encoded.key] = encoded.dataUri;
    }
  }

  return assets;
}

function writeManifest(assets) {
  ensureDir(OUT_DIR);

  const content = `// Auto-generated by scripts/encode-assets.js — do not edit manually
export const assetManifest = ${JSON.stringify(assets, null, 2)};
`;

  fs.writeFileSync(OUT_FILE, content);
  console.log(`Wrote manifest: ${OUT_FILE}`);
  console.log(`  Images: ${Object.keys(assets.images).length}`);
  console.log(`  Audio: ${Object.keys(assets.audio).length}`);
}

ensureDefaultAssets();
const assets = collectAssets(RAW_DIR);
writeManifest(assets);
